// Copy for the public showcase, FR first. Every product statement here maps to
// something the app actually does; demo data is synthetic and labelled as such
// on the page. No client names, usage figures or testimonials exist yet — do
// not add any until they are real.

// Set to a real address to show contact links; null hides them everywhere.
export const CONTACT_EMAIL = null

// Canonical skill counts per matching engine (services/skill_vocabulary_service).
export const ENGINES = [
  { key: 'general', count: 202, skills: ['javascript', 'react', 'docker', 'airflow'] },
  { key: 'bfsi', count: 110, skills: ['accounts payable', 'audit planning', 'basel iii'] },
  { key: 'sales', count: 122, skills: ['b2b sales', 'account planning', 'bant qualification'] },
  { key: 'marketing', count: 155, skills: ['brand management', 'product marketing', 'pricing strategy'] },
  { key: 'hr', count: 118, skills: ['applicant tracking system', 'benefits administration', 'boolean search'] },
  { key: 'health', count: 135, skills: ['aseptic technique', 'airway management', 'acls'] },
  { key: 'industrial', count: 157, skills: ['preventive maintenance', 'sap pm', 'cmms / eam'] },
  { key: 'customer_relations', count: 163, skills: ['inbound call handling', 'live chat support', 'omnichannel support'] },
  { key: 'logistics', count: 114, skills: ['order fulfilment', 'rf scanning', 'stock replenishment'] },
]

// Synthetic applications for the screening funnel demo, already ranked.
export const FUNNEL_ROWS = [
  { id: 'C-0412', composite: 91, ai: 88 },
  { id: 'C-0388', composite: 88, ai: 84 },
  { id: 'C-0371', composite: 86, ai: 86 },
  { id: 'C-0455', composite: 83, ai: 79 },
  { id: 'C-0419', composite: 81, ai: 77 },
  { id: 'C-0402', composite: 79, ai: 71 },
  { id: 'C-0364', composite: 76, ai: 70 },
  { id: 'C-0431', composite: 74, ai: 66 },
  { id: 'C-0397', composite: 71, ai: 63 },
  { id: 'C-0446', composite: 68, ai: 58 },
  { id: 'C-0380', composite: 64, ai: 55 },
  { id: 'C-0425', composite: 61, ai: 49 },
]

const fr = {
  meta: {
    home: 'RHIA — Recrutement assisté par IA',
    companies: 'Entreprises — RHIA',
    candidates: 'Candidats — RHIA',
    trust: 'Confiance et données — RHIA',
  },
  nav: {
    home: 'Accueil',
    companies: 'Entreprises',
    candidates: 'Candidats',
    trust: 'Confiance',
    recruiter: 'Espace recruteur',
    candidate: 'Espace candidat',
    mySpace: 'Mon espace',
    menu: 'Menu',
    close: 'Fermer le menu',
    language: 'Langue',
    skip: 'Aller au contenu',
    primary: 'Navigation principale',
  },
  synthetic: 'Données fictives',
  syntheticNote: 'Les documents présentés sont des démonstrations construites avec des données fictives.',
  close: { candidateSecondary: 'Comment vos données sont traitées' },
  common: {
    recruiterCta: 'Ouvrir l’espace recruteur',
    candidateCta: 'Créer mon compte candidat',
    jobSeeker: 'Je cherche un emploi',
    contact: 'Écrire à l’équipe',
    readMore: 'En savoir plus',
  },

  // ── Hero dossier spread ─────────────────────────────────────────────────
  spread: {
    label: 'Démonstration · données fictives',
    jobTag: 'Fiche de poste',
    jobTitle: 'Développeur·se Full-Stack',
    jobMeta: 'CDI · Hybride · Tunis',
    jobEngine: 'Moteur général & tech',
    jobSkills: 'Compétences requises',
    cvTag: 'CV',
    cvRole: 'Développeur web · 4 ans',
    cvMasked: 'Masqué avant l’analyse IA',
    cvExp: 'Expérience',
    cvExpTitle: 'Développeur web — plateforme logistique, 2022–2026',
    cvExp1: ['Interfaces ', 'React.js', ' et ', 'TypeScript', ' pour le suivi des livraisons'],
    cvExp2: ['API ', 'NodeJS', ' et base ', 'Postgres', ', conteneurisées avec ', 'Docker'],
    cvEdu: 'Formation',
    cvEduTitle: 'Diplôme d’ingénieur en informatique, 2022',
    cvSkills: 'Compétences',
    scoreTag: 'Correspondance',
    scoreRequired: 'Compétences requises',
    scoreMissing: 'Manquante',
    scoreRank: 'Rang',
    scoreRankValue: '4 sur 57',
    scoreStatus: 'Présélection',
    replay: 'Rejouer la démonstration',
  },

  home: {
    hero: {
      titleBefore: 'Recrutez sur des ',
      titleMark: 'preuves',
      titleAfter: ', pas sur des impressions.',
      lead: 'RHIA lit chaque candidature à la lumière de votre offre, classe les profils selon les seuils que vous fixez, puis prend en charge quiz et entretiens. La décision reste la vôtre.',
    },
    journey: {
      title: 'Une offre, du brouillon à la décision.',
      lead: 'Six étapes, un seul dossier. Chacune y dépose ses preuves, que vous pouvez relire à tout moment.',
      stages: [
        {
          key: 'offer',
          tab: 'Offre',
          title: 'Collez l’annonce, RHIA prépare le formulaire.',
          body: 'Intitulé, contrat, mode de travail, expérience et compétences sont proposés à partir de votre texte. Les compétences sont rattachées au vocabulaire du moteur de votre métier ; celles qu’il ne connaît pas vous sont signalées plutôt qu’inventées.',
          note: 'Rien n’est enregistré sans votre relecture.',
        },
        {
          key: 'applications',
          tab: 'Candidatures',
          title: 'Un CV devient un profil, sans livrer l’identité au modèle.',
          body: 'Nom, e-mail, téléphone, date de naissance, adresse et liens de profil sont masqués avant que le texte n’atteigne le modèle de langage. Le profil structuré qui en sort parle le même vocabulaire que vos offres.',
          note: 'Import en lot : RHIA analyse les CV, vous confirmez.',
        },
        {
          key: 'screening',
          tab: 'Présélection',
          title: 'Vous fixez les seuils. RHIA classe et justifie.',
          body: 'Un score composite — moteur de compétences et similarité sémantique — retient les X premiers. Un modèle de langage note ensuite chacun d’eux et rédige sa justification ; les Y meilleurs reçoivent le quiz, les Z premiers passent en entretien.',
          note: 'À la date limite de l’offre, la présélection peut se lancer seule.',
        },
        {
          key: 'quiz',
          tab: 'Quiz',
          title: 'Des QCM tirés de vos propres documents.',
          body: 'Déposez une documentation technique, un référentiel ou un support interne : RHIA en génère un questionnaire à choix multiples que vous relisez avant publication. Les présélectionnés le reçoivent automatiquement.',
          note: 'Les résultats remontent dans le dossier du candidat.',
        },
        {
          key: 'interview',
          tab: 'Entretien',
          title: 'L’entretien en visio, transcrit pendant qu’il a lieu.',
          body: 'Proposez des créneaux, synchronisez Google Agenda, menez l’entretien dans le navigateur. Vous suivez la transcription et des indicateurs d’attention et d’émotion ; à la fin, un rapport résume points forts, points faibles et un score sur 100.',
          note: 'Le flux audio et vidéo brut n’est jamais enregistré.',
        },
        {
          key: 'decision',
          tab: 'Décision',
          title: 'La décision reste la vôtre.',
          body: 'RHIA ordonne les preuves ; il ne recrute personne. L’automatisation fait avancer des candidatures, elle n’en rejette aucune. Vous changez le statut, le candidat est notifié.',
          note: 'Chaque étape reste consultable dans le dossier.',
        },
      ],
    },
    engines: {
      title: 'Neuf moteurs, un vocabulaire par métier.',
      lead: 'La correspondance des compétences ne repose pas sur un modèle généraliste. Chaque famille de métiers a son moteur et son vocabulaire canonique : « JS », « Javascript » et « Java Script » désignent la même compétence, et le formulaire d’offre vous oriente vers les termes que le moteur reconnaît.',
      total: 'compétences canoniques',
      skills: 'compétences',
      count: '9 moteurs',
    },
    doors: {
      companies: {
        title: 'Pour les entreprises',
        lines: ['Offres rédigées à partir de votre annonce', 'Présélection paramétrable et justifiée', 'Quiz, entretiens, équipe et départements'],
      },
      candidates: {
        title: 'Pour les candidats',
        lines: ['Profil pré-rempli depuis votre CV', 'Candidature en un clic, suivi de chaque étape', 'Quiz et entretiens depuis le navigateur'],
      },
    },
    trust: {
      title: 'Conçu pour des données qui ne vous appartiennent pas.',
      items: [
        { k: 'Avant l’IA', v: 'L’identité est retirée du CV avant toute analyse par le modèle de langage.' },
        { k: 'Pendant l’entretien', v: 'Aucun enregistrement audio ou vidéo brut. Seuls la transcription, des indicateurs dérivés et le rapport sont conservés.' },
        { k: 'À chaque connexion', v: 'Double authentification par application ou e-mail, rôles par équipe, tentatives limitées.' },
      ],
      link: 'Tout ce que RHIA conserve, et ce qu’il ne conserve pas',
    },
    close: {
      title: 'Votre prochaine embauche commence par un meilleur dossier.',
      lead: 'Les comptes entreprise sont ouverts par l’équipe RHIA. Vous avez déjà vos accès ? Entrez dans l’espace recruteur.',
    },
  },

  // ── Shared demo documents ───────────────────────────────────────────────
  docs: {
    draft: {
      pasteTag: 'Annonce collée',
      paste: 'Nous recrutons un·e développeur·se full-stack en CDI, en hybride à Tunis. 3 ans d’expérience minimum. Stack : React, TypeScript, NodeJS, PostgreSQL, Docker. Un plus : AWS et Figma.',
      formTag: 'Formulaire proposé',
      fields: [
        ['Intitulé', 'Développeur·se Full-Stack'],
        ['Contrat', 'CDI'],
        ['Mode', 'Hybride · Tunis'],
        ['Expérience', '3 à 5 ans'],
        ['Catégorie', 'Informatique & tech'],
      ],
      skills: 'Compétences',
      bonus: 'Bonus',
      review: 'À vérifier',
      reviewNote: 'inconnu du moteur, à ajouter à la main',
      proposed: 'proposé',
    },
    redact: {
      rawTag: 'CV reçu',
      modelTag: 'Ce que lit le modèle',
      profileTag: 'Profil structuré',
      rows: [['Expériences', '2'], ['Formation', '1'], ['Langues', 'FR · EN · AR']],
      skills: 'Compétences reconnues',
    },
    funnel: {
      tag: 'Présélection',
      received: 'candidatures',
      others: 'autres candidatures',
      x: 'Score composite · top X',
      y: 'Score IA · top Y',
      z: 'Entretien · top Z',
      composite: 'Composite',
      ai: 'IA',
      statuses: { received: 'Reçue', review: 'Présélection', quiz: 'Quiz', interview: 'Entretien' },
      justification: '« Maîtrise démontrée de React et NodeJS sur un produit en production ; AWS non mentionné. »',
      justificationTag: 'Justification · C-0412',
      decrease: 'Diminuer',
      increase: 'Augmenter',
      hint: 'Réglez les seuils',
      status: 'Statut',
    },
    quiz: {
      tag: 'QCM généré',
      source: 'Source : guide-technique-api.pdf',
      q1: 'Quel code HTTP l’API renvoie-t-elle lorsqu’un jeton d’accès a expiré ?',
      a1: ['400', '401', '403', '404'],
      q2: 'Quelle option reconstruit l’image d’un service sans utiliser le cache ?',
      a2: ['--pull', '--no-cache', '--squash', '--rm'],
      review: 'Relu par le recruteur avant publication',
    },
    interview: {
      tag: 'Entretien en direct',
      live: 'En direct',
      recruiter: 'Recruteur',
      candidate: 'Candidat',
      lines: [
        ['r', 'Comment avez-vous organisé le déploiement de l’API ?'],
        ['c', 'Chaque service avait son conteneur Docker, et la pipeline lançait les tests avant chaque mise en production.'],
        ['r', 'Et lorsqu’un test échouait en préproduction ?'],
        ['c', 'Le déploiement s’arrêtait, l’équipe recevait une alerte et on corrigeait sur une branche dédiée.'],
      ],
      indicators: [['Attention', 'Regard vers l’écran'], ['Visage', 'Neutre'], ['Voix', 'Calme']],
      reportTag: 'Rapport de fin d’appel',
      strengths: 'Points forts',
      strengthsList: ['Explications structurées', 'Maîtrise du déploiement'],
      weaknesses: 'À approfondir',
      weaknessesList: ['Peu d’exemples de tests de charge'],
      score: 'Score',
    },
    decision: {
      tag: 'Décision',
      candidate: 'C-0412 · Développeur·se Full-Stack',
      evidence: [['Correspondance', '86'], ['Score IA', '88'], ['Quiz', '17 / 20'], ['Entretien', '78 / 100']],
      stamp: 'Retenu',
      by: 'Décidé par : recruteur',
    },
  },

  // ── /entreprises ────────────────────────────────────────────────────────
  companies: {
    hero: {
      title: 'Le poste de travail du recruteur.',
      lead: 'De la rédaction de l’offre à l’entretien, chaque outil travaille sur le même dossier — et sous votre contrôle. Les comptes entreprise sont ouverts par l’équipe RHIA.',
    },
    tabsLabel: 'Sections de la page',
    sections: [
      {
        key: 'offers',
        tab: 'Offres',
        title: 'Rédigez une offre en relisant, pas en recopiant.',
        body: 'Collez une annonce existante : RHIA remplit le formulaire d’offre et vous laisse corriger. Les présentations de votre entreprise sont enregistrées une fois, puis choisies d’un clic dans chaque offre.',
        points: [
          'Champs proposés, jamais enregistrés sans vous',
          'Suggestions « vouliez-vous dire » sur chaque compétence saisie',
          'Compétences bonus pour départager les profils complets',
        ],
      },
      {
        key: 'applications',
        tab: 'Candidatures',
        title: 'Tous les CV, un seul format.',
        body: 'Les candidatures arrivent avec un profil structuré. Les CV reçus par d’autres canaux s’importent en lot : RHIA les analyse, les met en attente, et vous confirmez ceux à ajouter à l’offre.',
        points: [
          'Identité masquée avant l’analyse par le modèle',
          'Expériences, formations, langues et compétences extraites',
          'Compétences reliées au vocabulaire du moteur de l’offre',
        ],
      },
      {
        key: 'screening',
        tab: 'Présélection',
        title: 'Un classement que vous pouvez expliquer.',
        body: 'Vous choisissez combien de candidats passent chaque étape. RHIA calcule un score composite, demande à un modèle de langage une note justifiée, puis envoie le quiz et propose les entretiens — à la date limite de l’offre si vous le souhaitez.',
        points: [
          'Seuils X, Y et Z réglables offre par offre',
          'Justification écrite pour chaque score IA',
          'Aucune candidature rejetée automatiquement',
        ],
      },
      {
        key: 'quiz',
        tab: 'Quiz',
        title: 'Évaluez sur votre contenu, pas sur un test générique.',
        body: 'Déposez un ou plusieurs documents : RHIA en tire des QCM, que vous pouvez enregistrer comme modèles. Les questions se modifient avant publication et les résultats s’ajoutent au dossier.',
        points: [
          'Génération à partir de plusieurs documents',
          'Modèles réutilisables d’une offre à l’autre',
          'Envoi automatique aux présélectionnés',
        ],
      },
      {
        key: 'interviews',
        tab: 'Entretiens',
        title: 'Planifier, mener, relire.',
        body: 'Proposez des créneaux au candidat, synchronisez-les avec Google Agenda, puis menez l’entretien dans le navigateur. La transcription est produite sur le serveur de la plateforme ; le rapport de fin d’appel arrive dans le dossier.',
        points: [
          'Créneaux proposés et confirmés par e-mail',
          'Indicateurs d’attention et d’émotion en direct',
          'Rapport : synthèse, points forts, points faibles, score sur 100',
        ],
      },
      {
        key: 'team',
        tab: 'Équipe',
        title: 'Chacun voit ce qui le concerne.',
        body: 'Organisez l’entreprise en départements et invitez vos collègues par e-mail. Les rôles déterminent qui crée les offres, qui évalue et qui administre ; le calendrier et les notifications sont partagés.',
        points: [
          'Rôles : administrateur, recruteur, chef de département',
          'Départements avec leurs propres offres',
          'Double authentification pour les comptes recruteurs',
        ],
      },
    ],
    team: {
      tag: 'Équipe',
      roles: [
        ['Administrateur', 'Entreprise, équipe, paramètres'],
        ['Recruteur', 'Offres, candidatures, entretiens'],
        ['Chef de département', 'Offres et candidats de son département'],
      ],
      departments: 'Départements',
      deptList: ['Ingénierie', 'Finance', 'Opérations'],
    },
    slots: {
      tag: 'Créneaux proposés',
      list: ['Mar. 14 oct. · 10:00', 'Mar. 14 oct. · 14:30', 'Jeu. 16 oct. · 09:30'],
      chosen: 'Choisi par le candidat',
      calendar: 'Ajouté à Google Agenda',
    },
  },

  // ── /candidats ──────────────────────────────────────────────────────────
  candidates: {
    hero: {
      title: 'Votre CV fait le premier pas.',
      lead: 'Déposez votre CV : RHIA pré-remplit votre profil. Postulez en un clic, suivez chaque étape, passez quiz et entretiens depuis votre navigateur.',
    },
    close: {
      title: 'Votre prochain poste commence par un profil complet.',
      lead: 'Créez votre compte, déposez votre CV et postulez aux offres publiées par les entreprises.',
    },
    tabsLabel: 'Sections de la page',
    sections: [
      {
        key: 'profile',
        tab: 'Profil',
        title: 'Un profil complet sans tout ressaisir.',
        body: 'Votre CV est analysé et pré-remplit les huit étapes de votre profil : expériences, formations, compétences, langues. Vous relisez, corrigez, et c’est prêt.',
        points: ['Vos coordonnées sont masquées avant l’analyse IA', 'Compétences rattachées aux termes utilisés par les recruteurs'],
      },
      {
        key: 'jobs',
        tab: 'Offres',
        title: 'Cherchez, enregistrez, postulez.',
        body: 'Filtrez les offres publiées par les entreprises, gardez celles qui vous intéressent et postulez avec votre profil en un clic.',
        points: ['Offres enregistrées pour plus tard', 'Candidature avec le profil déjà rempli'],
      },
      {
        key: 'tracking',
        tab: 'Suivi',
        title: 'Vous savez toujours où en est votre candidature.',
        body: 'Chaque changement de statut vous est notifié. Le détail de chaque candidature montre l’étape en cours, les quiz à passer et les entretiens à venir.',
        points: ['Notifications à chaque étape', 'Historique de toutes vos candidatures'],
      },
      {
        key: 'interview',
        tab: 'Entretien',
        title: 'Quiz et entretiens, sans rien installer.',
        body: 'Les quiz se passent dans le navigateur. Pour l’entretien, choisissez un créneau parmi ceux proposés, puis rejoignez la salle en visio — avec un flou d’arrière-plan si vous le souhaitez.',
        points: ['Choix du créneau parmi les propositions', 'Flou d’arrière-plan intégré', 'Analyse comportementale uniquement caméra activée'],
      },
      {
        key: 'skills',
        tab: 'Compétences',
        title: 'Voyez où vous mènent vos compétences.',
        body: 'L’analyse de votre profil suggère les métiers qui vous correspondent, les compétences qui comptent le plus et celles à acquérir pour viser un autre poste.',
        points: ['Profils de métier recommandés', 'Pistes de montée en compétences'],
      },
      {
        key: 'data',
        tab: 'Vos données',
        title: 'Vos données restent à vous.',
        body: 'Exportez l’ensemble de vos données en un fichier, ou supprimez votre compte depuis vos paramètres. Activez la double authentification par application ou par e-mail.',
        points: ['Export complet au format JSON', 'Suppression du compte en libre-service', 'Double authentification'],
      },
    ],
    setup: {
      tag: 'Profil · pré-rempli depuis le CV',
      steps: ['Identité', 'Poste visé', 'Expériences', 'Formations', 'Compétences', 'Langues', 'Préférences', 'Validation'],
      filled: 'pré-rempli',
      check: 'à relire',
    },
    jobs: {
      tag: 'Offres',
      search: 'Développeur',
      list: [
        ['Développeur·se Full-Stack', 'CDI · Hybride · Tunis'],
        ['Ingénieur·e Data', 'CDI · Sur site · Sfax'],
        ['Développeur·se Mobile', 'CDD · Télétravail'],
      ],
      apply: 'Postuler',
      saved: 'Enregistrée',
    },
    track: {
      tag: 'Ma candidature · Développeur·se Full-Stack',
      steps: ['Soumise', 'Présélection', 'Quiz', 'Entretien', 'Décision'],
      current: 'Entretien jeu. 16 oct. · 09:30',
    },
    room: {
      tag: 'Salle d’entretien',
      blur: 'Flou d’arrière-plan',
      cam: 'Caméra',
      mic: 'Micro',
      join: 'Rejoindre',
    },
    insights: {
      tag: 'Analyse de compétences',
      recommended: 'Profils recommandés',
      roles: [['Développeur·se Full-Stack', 92], ['Développeur·se Front-end', 85], ['Ingénieur·e DevOps', 61]],
      next: 'Pour viser « Ingénieur·e DevOps »',
      learn: ['kubernetes', 'terraform', 'aws'],
    },
    data: {
      tag: 'Paramètres · Données',
      export: 'Exporter mes données',
      delete: 'Supprimer mon compte',
      twofa: 'Double authentification',
      on: 'Activée',
    },
  },

  // ── /confiance ──────────────────────────────────────────────────────────
  trust: {
    hero: {
      title: 'Ce que RHIA fait de vos données — et ce qu’il ne fait pas.',
      lead: 'Un recrutement manipule des CV, des visages, des voix. Voici, étape par étape, ce qui est analysé, ce qui est conservé et ce qui ne l’est jamais.',
    },
    ledger: {
      title: 'Le registre',
      cols: ['Étape', 'Ce qui se passe', 'Conservé', 'N’arrive jamais'],
      rows: [
        {
          step: 'Analyse du CV',
          what: 'Le texte du CV est envoyé au modèle de langage pour en extraire un profil.',
          kept: 'Le profil structuré, le fichier du CV',
          never: 'Nom, e-mail, téléphone, date de naissance, adresse et liens de profil dans le texte transmis au modèle — remplacés par [NAME], [EMAIL]…',
        },
        {
          step: 'Présélection',
          what: 'Score composite, puis note d’un modèle de langage avec justification écrite.',
          kept: 'Scores, rang, justification',
          never: 'Aucun rejet automatique : l’automatisation ne fait qu’avancer des candidatures',
        },
        {
          step: 'Entretien vidéo',
          what: 'Pendant l’appel, des modèles produisent des indicateurs d’émotion et d’attention, et une transcription.',
          kept: 'Étiquettes dérivées, transcription, rapport de fin d’appel',
          never: 'Le flux audio et vidéo brut : l’appel n’est pas enregistré',
        },
        {
          step: 'Transcription',
          what: 'L’audio de l’entretien est transcrit par un modèle exécuté sur le serveur de la plateforme.',
          kept: 'Le texte transcrit',
          never: 'Aucun envoi à un service tiers de reconnaissance vocale',
        },
      ],
    },
    principles: {
      title: 'Les garanties, une par une.',
      items: [
        { t: 'L’identité retirée avant le modèle', d: 'Un moteur de détection masque les données personnelles du CV avant tout appel au modèle de langage, qui ne voit que des balises comme [NAME] ou [EMAIL].' },
        { t: 'La caméra sous votre contrôle', d: 'L’analyse comportementale ne fonctionne que caméra et micro activés. Un candidat peut la refuser en désactivant sa caméra.' },
        { t: 'Une décision humaine', d: 'Les scores ordonnent les candidatures ; le statut final est toujours changé par un membre de l’équipe. Le candidat peut demander une intervention humaine et contester une évaluation.' },
        { t: 'Des accès verrouillés', d: 'Double authentification par application d’authentification ou par e-mail, tentatives de connexion limitées, rôles par équipe et journal d’audit côté plateforme.' },
        { t: 'Des droits en libre-service', d: 'Chaque candidat peut exporter toutes ses données au format JSON ou supprimer son compte depuis ses paramètres.' },
        { t: 'Des contenus traités comme non fiables', d: 'Une annonce collée dans le formulaire d’offre est transmise au modèle comme une donnée à analyser, jamais comme une instruction à suivre.' },
      ],
    },
    terms: 'Lire les conditions d’utilisation et la politique de confidentialité',
  },

  footer: {
    tagline: 'Recrutement assisté par IA, décision humaine.',
    product: 'Produit',
    access: 'Accès',
    legal: 'Légal',
    terms: 'Conditions & confidentialité',
    rights: '© 2026 RHIA. Tous droits réservés.',
  },

  engineNames: {
    general: 'Général & tech',
    bfsi: 'Comptabilité & finance',
    sales: 'Commercial',
    marketing: 'Marketing',
    hr: 'RH & administration',
    health: 'Santé & paramédical',
    industrial: 'Industrie & maintenance',
    customer_relations: 'Relation client & BPO',
    logistics: 'Logistique & supply chain',
  },
}

const en = {
  meta: {
    home: 'RHIA — AI-assisted recruitment',
    companies: 'Companies — RHIA',
    candidates: 'Candidates — RHIA',
    trust: 'Trust & data — RHIA',
  },
  nav: {
    home: 'Home',
    companies: 'Companies',
    candidates: 'Candidates',
    trust: 'Trust',
    recruiter: 'Recruiter space',
    candidate: 'Candidate space',
    mySpace: 'My space',
    menu: 'Menu',
    close: 'Close menu',
    language: 'Language',
    skip: 'Skip to content',
    primary: 'Main navigation',
  },
  synthetic: 'Synthetic data',
  syntheticNote: 'The documents shown are demonstrations built with synthetic data.',
  close: { candidateSecondary: 'How your data is handled' },
  common: {
    recruiterCta: 'Open the recruiter space',
    candidateCta: 'Create my candidate account',
    jobSeeker: 'I’m looking for a job',
    contact: 'Write to the team',
    readMore: 'Learn more',
  },

  spread: {
    label: 'Demo · synthetic data',
    jobTag: 'Job sheet',
    jobTitle: 'Full-Stack Developer',
    jobMeta: 'Permanent · Hybrid · Tunis',
    jobEngine: 'General & tech engine',
    jobSkills: 'Required skills',
    cvTag: 'CV',
    cvRole: 'Web developer · 4 years',
    cvMasked: 'Masked before AI analysis',
    cvExp: 'Experience',
    cvExpTitle: 'Web developer — logistics platform, 2022–2026',
    cvExp1: ['Built ', 'React.js', ' and ', 'TypeScript', ' interfaces for delivery tracking'],
    cvExp2: ['', 'NodeJS', ' APIs on a ', 'Postgres', ' database, containerised with ', 'Docker'],
    cvEdu: 'Education',
    cvEduTitle: 'Engineering degree in computer science, 2022',
    cvSkills: 'Skills',
    scoreTag: 'Match',
    scoreRequired: 'Required skills',
    scoreMissing: 'Missing',
    scoreRank: 'Rank',
    scoreRankValue: '4 of 57',
    scoreStatus: 'Shortlisted',
    replay: 'Replay the demo',
  },

  home: {
    hero: {
      titleBefore: 'Hire on ',
      titleMark: 'evidence',
      titleAfter: ', not on impressions.',
      lead: 'RHIA reads every application against your job offer, ranks candidates through thresholds you set, then runs the quiz and the interview. The decision stays yours.',
    },
    journey: {
      title: 'One job offer, from draft to decision.',
      lead: 'Six stages, one dossier. Each stage files its evidence, and you can reread all of it at any time.',
      stages: [
        {
          key: 'offer',
          tab: 'Offer',
          title: 'Paste the ad, RHIA prepares the form.',
          body: 'Title, contract, work mode, experience and skills are proposed from your text. Skills are tied to the vocabulary of your field’s engine; the ones it doesn’t know are flagged for you instead of being made up.',
          note: 'Nothing is saved until you review it.',
        },
        {
          key: 'applications',
          tab: 'Applications',
          title: 'A CV becomes a profile, without handing identity to the model.',
          body: 'Name, email, phone, birth date, address and profile links are masked before the text reaches the language model. The structured profile that comes out speaks the same vocabulary as your offers.',
          note: 'Bulk import: RHIA parses the CVs, you confirm.',
        },
        {
          key: 'screening',
          tab: 'Screening',
          title: 'You set the thresholds. RHIA ranks and explains.',
          body: 'A composite score — skill engine plus semantic similarity — keeps the top X. A language model then scores each of them and writes its justification; the best Y get the quiz, the top Z move on to interview.',
          note: 'At the offer’s deadline, screening can run on its own.',
        },
        {
          key: 'quiz',
          tab: 'Quiz',
          title: 'Multiple-choice quizzes drawn from your own documents.',
          body: 'Upload technical docs, a skills framework or internal material: RHIA generates a multiple-choice quiz that you review before publishing. Shortlisted candidates receive it automatically.',
          note: 'Results are filed in the candidate’s dossier.',
        },
        {
          key: 'interview',
          tab: 'Interview',
          title: 'Video interviews, transcribed as they happen.',
          body: 'Offer time slots, sync Google Calendar, run the interview in the browser. You follow the transcript and attention and emotion indicators; at the end, a report sums up strengths, weaknesses and a score out of 100.',
          note: 'Raw audio and video are never recorded.',
        },
        {
          key: 'decision',
          tab: 'Decision',
          title: 'The decision stays yours.',
          body: 'RHIA orders the evidence; it doesn’t hire anyone. Automation moves applications forward and never rejects one. You change the status, the candidate is notified.',
          note: 'Every stage stays on file in the dossier.',
        },
      ],
    },
    engines: {
      title: 'Nine engines, one vocabulary per field.',
      lead: 'Skill matching doesn’t rely on one general-purpose model. Each family of jobs has its own engine and canonical vocabulary: “JS”, “Javascript” and “Java Script” are the same skill, and the job form steers you toward the terms the engine recognises.',
      total: 'canonical skills',
      skills: 'skills',
      count: '9 engines',
    },
    doors: {
      companies: {
        title: 'For companies',
        lines: ['Offers drafted from your job ad', 'Configurable, explained screening', 'Quizzes, interviews, team and departments'],
      },
      candidates: {
        title: 'For candidates',
        lines: ['Profile pre-filled from your CV', 'One-click applications, every stage tracked', 'Quizzes and interviews in the browser'],
      },
    },
    trust: {
      title: 'Built for data that isn’t yours to lose.',
      items: [
        { k: 'Before the AI', v: 'Identity is stripped from the CV before any analysis by the language model.' },
        { k: 'During the interview', v: 'No raw audio or video is recorded. Only the transcript, derived indicators and the report are kept.' },
        { k: 'At every sign-in', v: 'Two-factor authentication by app or email, team roles, rate-limited attempts.' },
      ],
      link: 'Everything RHIA keeps, and everything it doesn’t',
    },
    close: {
      title: 'Your next hire starts with a better dossier.',
      lead: 'Company accounts are opened by the RHIA team. Already have access? Head to the recruiter space.',
    },
  },

  docs: {
    draft: {
      pasteTag: 'Pasted ad',
      paste: 'We’re hiring a full-stack developer, permanent contract, hybrid in Tunis. 3+ years of experience. Stack: React, TypeScript, NodeJS, PostgreSQL, Docker. Nice to have: AWS and Figma.',
      formTag: 'Proposed form',
      fields: [
        ['Title', 'Full-Stack Developer'],
        ['Contract', 'Permanent'],
        ['Mode', 'Hybrid · Tunis'],
        ['Experience', '3 to 5 years'],
        ['Category', 'IT & tech'],
      ],
      skills: 'Skills',
      bonus: 'Bonus',
      review: 'To review',
      reviewNote: 'unknown to the engine, add it by hand',
      proposed: 'proposed',
    },
    redact: {
      rawTag: 'CV received',
      modelTag: 'What the model reads',
      profileTag: 'Structured profile',
      rows: [['Experience', '2'], ['Education', '1'], ['Languages', 'FR · EN · AR']],
      skills: 'Recognised skills',
    },
    funnel: {
      tag: 'Screening',
      received: 'applications',
      others: 'more applications',
      x: 'Composite score · top X',
      y: 'AI score · top Y',
      z: 'Interview · top Z',
      composite: 'Composite',
      ai: 'AI',
      statuses: { received: 'Received', review: 'Shortlisted', quiz: 'Quiz', interview: 'Interview' },
      justification: '“Proven React and NodeJS work on a production product; AWS not mentioned.”',
      justificationTag: 'Justification · C-0412',
      decrease: 'Decrease',
      increase: 'Increase',
      hint: 'Set the thresholds',
      status: 'Status',
    },
    quiz: {
      tag: 'Generated quiz',
      source: 'Source: api-technical-guide.pdf',
      q1: 'Which HTTP status does the API return when an access token has expired?',
      a1: ['400', '401', '403', '404'],
      q2: 'Which option rebuilds a service image without using the cache?',
      a2: ['--pull', '--no-cache', '--squash', '--rm'],
      review: 'Reviewed by the recruiter before publishing',
    },
    interview: {
      tag: 'Live interview',
      live: 'Live',
      recruiter: 'Recruiter',
      candidate: 'Candidate',
      lines: [
        ['r', 'How did you organise the API deployment?'],
        ['c', 'Each service had its own Docker container, and the pipeline ran the tests before every release.'],
        ['r', 'And when a test failed in staging?'],
        ['c', 'The deployment stopped, the team got an alert, and we fixed it on a dedicated branch.'],
      ],
      indicators: [['Attention', 'Looking at screen'], ['Face', 'Neutral'], ['Voice', 'Calm']],
      reportTag: 'End-of-call report',
      strengths: 'Strengths',
      strengthsList: ['Structured explanations', 'Solid on deployment'],
      weaknesses: 'To dig into',
      weaknessesList: ['Few examples of load testing'],
      score: 'Score',
    },
    decision: {
      tag: 'Decision',
      candidate: 'C-0412 · Full-Stack Developer',
      evidence: [['Match', '86'], ['AI score', '88'], ['Quiz', '17 / 20'], ['Interview', '78 / 100']],
      stamp: 'Hired',
      by: 'Decided by: recruiter',
    },
  },

  companies: {
    hero: {
      title: 'The recruiter’s workbench.',
      lead: 'From drafting the offer to the interview, every tool works on the same dossier — under your control. Company accounts are opened by the RHIA team.',
    },
    tabsLabel: 'Page sections',
    sections: [
      {
        key: 'offers',
        tab: 'Offers',
        title: 'Write an offer by reviewing, not retyping.',
        body: 'Paste an existing ad: RHIA fills in the job form and lets you correct it. Your company presentations are saved once, then picked in one click for each offer.',
        points: [
          'Fields proposed, never saved without you',
          '“Did you mean” suggestions on every skill you type',
          'Bonus skills to tell fully-matched profiles apart',
        ],
      },
      {
        key: 'applications',
        tab: 'Applications',
        title: 'Every CV, one format.',
        body: 'Applications arrive with a structured profile. CVs received through other channels can be imported in bulk: RHIA parses them, stages them, and you confirm which ones join the offer.',
        points: [
          'Identity masked before the model reads it',
          'Experience, education, languages and skills extracted',
          'Skills tied to the offer’s engine vocabulary',
        ],
      },
      {
        key: 'screening',
        tab: 'Screening',
        title: 'A ranking you can explain.',
        body: 'You choose how many candidates pass each stage. RHIA computes a composite score, asks a language model for a justified score, then sends the quiz and proposes interviews — at the offer’s deadline if you want.',
        points: [
          'X, Y and Z thresholds set per offer',
          'A written justification for every AI score',
          'No application is ever rejected automatically',
        ],
      },
      {
        key: 'quiz',
        tab: 'Quiz',
        title: 'Assess on your content, not a generic test.',
        body: 'Upload one or more documents: RHIA turns them into multiple-choice questions you can save as templates. Questions can be edited before publishing, and results are added to the dossier.',
        points: [
          'Generated from several documents at once',
          'Templates reusable across offers',
          'Sent automatically to shortlisted candidates',
        ],
      },
      {
        key: 'interviews',
        tab: 'Interviews',
        title: 'Schedule, run, review.',
        body: 'Offer time slots to the candidate, sync them with Google Calendar, then run the interview in the browser. Transcription runs on the platform’s own server; the end-of-call report lands in the dossier.',
        points: [
          'Slots proposed and confirmed by email',
          'Live attention and emotion indicators',
          'Report: summary, strengths, weaknesses, score out of 100',
        ],
      },
      {
        key: 'team',
        tab: 'Team',
        title: 'Everyone sees what concerns them.',
        body: 'Organise the company into departments and invite colleagues by email. Roles decide who creates offers, who evaluates and who administers; the calendar and notifications are shared.',
        points: [
          'Roles: admin, recruiter, head of department',
          'Departments with their own offers',
          'Two-factor authentication for recruiter accounts',
        ],
      },
    ],
    team: {
      tag: 'Team',
      roles: [
        ['Admin', 'Company, team, settings'],
        ['Recruiter', 'Offers, applications, interviews'],
        ['Head of department', 'Their department’s offers and candidates'],
      ],
      departments: 'Departments',
      deptList: ['Engineering', 'Finance', 'Operations'],
    },
    slots: {
      tag: 'Proposed slots',
      list: ['Tue 14 Oct · 10:00', 'Tue 14 Oct · 14:30', 'Thu 16 Oct · 09:30'],
      chosen: 'Picked by the candidate',
      calendar: 'Added to Google Calendar',
    },
  },

  candidates: {
    hero: {
      title: 'Your CV makes the first move.',
      lead: 'Upload your CV: RHIA pre-fills your profile. Apply in one click, follow every stage, take quizzes and interviews from your browser.',
    },
    close: {
      title: 'Your next job starts with a complete profile.',
      lead: 'Create your account, upload your CV and apply to the offers companies publish.',
    },
    tabsLabel: 'Page sections',
    sections: [
      {
        key: 'profile',
        tab: 'Profile',
        title: 'A complete profile without retyping it all.',
        body: 'Your CV is analysed and pre-fills the eight steps of your profile: experience, education, skills, languages. You review, correct, and you’re done.',
        points: ['Your contact details are masked before AI analysis', 'Skills tied to the terms recruiters use'],
      },
      {
        key: 'jobs',
        tab: 'Jobs',
        title: 'Search, save, apply.',
        body: 'Filter the offers companies publish, save the ones you like and apply with your profile in one click.',
        points: ['Saved offers for later', 'Applications with your profile already filled in'],
      },
      {
        key: 'tracking',
        tab: 'Tracking',
        title: 'You always know where your application stands.',
        body: 'Every status change is notified. Each application’s detail shows the current stage, quizzes to take and upcoming interviews.',
        points: ['Notifications at every stage', 'History of all your applications'],
      },
      {
        key: 'interview',
        tab: 'Interview',
        title: 'Quizzes and interviews, nothing to install.',
        body: 'Quizzes run in the browser. For the interview, pick one of the proposed slots, then join the video room — with background blur if you like.',
        points: ['Pick a slot among those proposed', 'Built-in background blur', 'Behavioural analysis only with the camera on'],
      },
      {
        key: 'skills',
        tab: 'Skills',
        title: 'See where your skills can take you.',
        body: 'Your profile analysis suggests the roles that fit you, the skills that matter most and the ones to learn to aim for another job.',
        points: ['Recommended job profiles', 'Upskilling paths'],
      },
      {
        key: 'data',
        tab: 'Your data',
        title: 'Your data stays yours.',
        body: 'Export all your data as one file, or delete your account from your settings. Turn on two-factor authentication by app or email.',
        points: ['Full export as JSON', 'Self-service account deletion', 'Two-factor authentication'],
      },
    ],
    setup: {
      tag: 'Profile · pre-filled from CV',
      steps: ['Identity', 'Target role', 'Experience', 'Education', 'Skills', 'Languages', 'Preferences', 'Review'],
      filled: 'pre-filled',
      check: 'to review',
    },
    jobs: {
      tag: 'Jobs',
      search: 'Developer',
      list: [
        ['Full-Stack Developer', 'Permanent · Hybrid · Tunis'],
        ['Data Engineer', 'Permanent · On site · Sfax'],
        ['Mobile Developer', 'Fixed-term · Remote'],
      ],
      apply: 'Apply',
      saved: 'Saved',
    },
    track: {
      tag: 'My application · Full-Stack Developer',
      steps: ['Submitted', 'Shortlisted', 'Quiz', 'Interview', 'Decision'],
      current: 'Interview Thu 16 Oct · 09:30',
    },
    room: {
      tag: 'Interview room',
      blur: 'Background blur',
      cam: 'Camera',
      mic: 'Mic',
      join: 'Join',
    },
    insights: {
      tag: 'Skills analysis',
      recommended: 'Recommended profiles',
      roles: [['Full-Stack Developer', 92], ['Front-end Developer', 85], ['DevOps Engineer', 61]],
      next: 'To aim for “DevOps Engineer”',
      learn: ['kubernetes', 'terraform', 'aws'],
    },
    data: {
      tag: 'Settings · Data',
      export: 'Export my data',
      delete: 'Delete my account',
      twofa: 'Two-factor authentication',
      on: 'On',
    },
  },

  trust: {
    hero: {
      title: 'What RHIA does with your data — and what it doesn’t.',
      lead: 'Hiring handles CVs, faces and voices. Here is, stage by stage, what gets analysed, what gets kept and what never is.',
    },
    ledger: {
      title: 'The ledger',
      cols: ['Stage', 'What happens', 'Kept', 'Never happens'],
      rows: [
        {
          step: 'CV analysis',
          what: 'The CV text is sent to the language model to extract a profile.',
          kept: 'The structured profile, the CV file',
          never: 'Name, email, phone, birth date, address and profile links in the text sent to the model — replaced by [NAME], [EMAIL]…',
        },
        {
          step: 'Screening',
          what: 'Composite score, then a language-model score with a written justification.',
          kept: 'Scores, rank, justification',
          never: 'No automatic rejection: automation only moves applications forward',
        },
        {
          step: 'Video interview',
          what: 'During the call, models produce emotion and attention indicators, and a transcript.',
          kept: 'Derived labels, transcript, end-of-call report',
          never: 'The raw audio and video stream: the call is not recorded',
        },
        {
          step: 'Transcription',
          what: 'Interview audio is transcribed by a model running on the platform’s own server.',
          kept: 'The transcript text',
          never: 'Nothing is sent to a third-party speech-recognition service',
        },
      ],
    },
    principles: {
      title: 'The safeguards, one by one.',
      items: [
        { t: 'Identity removed before the model', d: 'A detection engine masks personal data in the CV before any call to the language model, which only sees tags such as [NAME] or [EMAIL].' },
        { t: 'The camera stays in your hands', d: 'Behavioural analysis only runs with camera and mic on. A candidate can refuse it by turning the camera off.' },
        { t: 'A human decision', d: 'Scores order the applications; the final status is always changed by a team member. Candidates can ask for human review and contest an assessment.' },
        { t: 'Locked-down access', d: 'Two-factor authentication by authenticator app or email, rate-limited sign-in attempts, team roles and a platform audit log.' },
        { t: 'Self-service rights', d: 'Every candidate can export all their data as JSON or delete their account from their settings.' },
        { t: 'Content treated as untrusted', d: 'A job ad pasted into the offer form reaches the model as data to analyse, never as instructions to follow.' },
      ],
    },
    terms: 'Read the terms of use and privacy policy',
  },

  footer: {
    tagline: 'AI-assisted recruitment, human decisions.',
    product: 'Product',
    access: 'Access',
    legal: 'Legal',
    terms: 'Terms & privacy',
    rights: '© 2026 RHIA. All rights reserved.',
  },

  engineNames: {
    general: 'General & tech',
    bfsi: 'Accounting & finance',
    sales: 'Sales',
    marketing: 'Marketing',
    hr: 'HR & administration',
    health: 'Health & paramedical',
    industrial: 'Industrial & maintenance',
    customer_relations: 'Customer relations & BPO',
    logistics: 'Logistics & supply chain',
  },
}

export const copy = { fr, en }
